### PR TITLE
Phil's edits to paper 2

### PR DESCRIPTION
**Pull request by drphilmarshall**
Started reading through suggesting re-wordings etc, I'll let you know when I'm done! Feel free to dispute/merge as I go :-) First commit was some abstract re-wordings.

### CODE REVIEW

**Comment by anupreeta27** [comment]
@drphilmarshall  please remember that abstract word limit is 250 and it is currently at the limit. So, if you've added words, you'll have to remove another word from somewhere.

**Comment by drphilmarshall** [comment]
I removed words, it turns out - we're now at 236.

**Comment by anupreeta27** [comment]
the "space warps" counts as two words because there's a space in between them, in case you have pasted "\sw" in the counter

**Comment by anupreeta27** [comment]
i managed to merge your version with mine with git :smile:

**Comment by drphilmarshall** [comment]
:-)

**Comment by drphilmarshall** [comment]
This PR can no longer be merged automatically - I'll git merge from master and resolve the conflicts.

**Comment by drphilmarshall** [comment]
OK @anupreeta27, I finished going through paper 2. Hope you like the rewording. I see appendix A is still there, fine if you want to keep that text there. Nice job! :-)

**Comment by aprajita** [comment]
@drphilmarshall how does anu deal with your edits and mine if she hasn't yet merged my edits?

**Comment by drphilmarshall** [comment]
@anupreeta27, you should:

1) merge automatically whichever PR can be merged, using the web interface
2) check to see if the other one can be merged, and if it can, merge it
using the web interface

If conflicts are detected,  you'll need to merge on the command line, like
this:

    git checkout pjm-paper2
    git pull origin pjm-paper2
    git checkout master
    git merge pjm-paper2

Then fix the conflicts using your editor. Search for "<<<" to find the
start of each conflict block. The bottom is marked by ">>>". The upper
block is what's in the master branch, the bottom block is what sin
pjm-paper2 (and it should be labelled that way).

When you've resolved the conflicts and done a `git add` on the resolved
files, you can commit and push back up to the web repo. The other pull
request will then update, and tell you whether it can be merged
automatically.

It doesn't matter whether you merge Aprajita's changes before or after
mine, git merge should sort as much out as it can, and if we have both made
edits in the same block of text you will have to figure out how to includ
eboth our inputs anyway. Good luck, Anu! Nearly there :-)

**Comment by anupreeta27** [comment]
@aprajita 
i haven't read this entire thread  but just to answer your question - see the main branch - i have incorporated your edits (most of them- except for a few which i will do later)...

**Comment by aprajita** [comment]
ok thanks

**Comment by drphilmarshall** [comment]
They need to add "citizen science" to their list of keywords - let's leave it in. Thanks for merging! :-)

**Comment by anupreeta27** [comment]
fine then, will leave it in.

**Pull request merged**
