### PR TITLE
abstract+concl. and few other edits in between

### PR DESCRIPTION
**Pull request by anupreeta27**
@drphilmarshall  please check.
...will try to do it section wise next.

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Great stuff, thanks Anu. I have merged into master and am fixing the bits marked `\new{}` now.

**Comment by drphilmarshall** [comment]
Interesting: merging on the command line closes a pull request automatically! Try making some more commits to `anu_paper1`, @anupreeta27 - hopefully that will reopen the pull request. Better tag the commits with `#208` just in case.

**Comment by aprajita** [comment]
why don't i see a thread like this for the changes I committed in av-paper1 - have I missed a step?

**Comment by drphilmarshall** [comment]
This is a pull request thread rather than an issue thread - if you go to
your av-paper1 branch, you should be able to open a pull request and then
I'll deal with the merge. Thanks! :-)

**Pull request merged**
